name: Build GraphScope Wheels on Linux

on:
  # Trigger the workflow on push or pull request, but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    #strategy:
      #matrix:
        #python-version: ['3.10', '3.11']

    steps:
    #- uses: actions/checkout@v2
      #with:
        #submodules: true

    #- name: Set up Python
      #uses: actions/setup-python@v2
      #with:
        #python-version: ${{ matrix.python-version }}

    - name: build
      run: |
        git clone -b develop --depth=1 https://github.com/lidongze0629/GraphScope.git

    - name: Setup tmate session
      if: false
      uses: mxschmitt/action-tmate@v2
