name: Build GraphScope Wheels on Linux

on:
  # Trigger the workflow on push or pull request, but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: build
      run: |
        echo "${{ GITHUB.REF }}"
        if [ "${{ GITHUB.REF }}" == "refs/heads/main" ];then echo "main process" && export xxx="debug"; fi
        echo "${xxx}"

    - name: Setup tmate session
      if: false
      uses: mxschmitt/action-tmate@v2
