name: Build GraphScope Wheels on Linux

on:
  # Trigger the workflow on push or pull request, but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-10.15
    strategy:
      matrix:
        python-version: ['3.7']

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        pushd $(brew --repo homebrew/core)
        git checkout 2b411d925849478163647594b32fd237828cf720
        popd

    - name: Setup tmate session
      if: true
      uses: mxschmitt/action-tmate@v2
