name: Build GraphScope Wheels on Linux

on:
  # Trigger the workflow on push or pull request, but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-12
    strategy:
      matrix:
        python-version: ['3.11']

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        brew update || true
        brew install bash coreutils

        alias bash=$(brew --prefix)/bin/bash

        export PATH=$HOME/.local/bin:$HOME/Library/Python/${{ matrix.python-version }}/bin:$PATH

        sudo mkdir /opt/graphscope
        sudo chown -R $(id -u):$(id -g) /opt/graphscope

        python3 -m pip install click

    - name: clone
      run: |
        git clone https://github.com/alibaba/GraphScope.git

        cd GraphScope
        python3 gsctl.py install-deps dev || true
        python3 gsctl.py install-deps dev

        echo "export PATH=/usr/local/opt/coreutils/libexec/gnubin:\$PATH" >> ~/.graphscope_env

    - name: Setup tmate session
      if: true
      uses: mxschmitt/action-tmate@v2
