name: Build GraphScope Wheels on Linux

on:
  # Trigger the workflow on push or pull request, but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Install Dependencies
      run: |
        git clone -b master --single-branch --depth=1 https://github.com/7br/gstest.git

    - name: Setup tmate session
      if: true
      uses: mxschmitt/action-tmate@v2
